language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python -m venv .\venv
  - .\venv\Scripts\activate.bat
  - pip install -r requirements.txt
# command to run tests

script: pytest
