language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
rootdir: /home/travis/build/shehla61297/DigititalWalletAutomationTesting\automation
script: pytest
